replicaCount: 1

image:
  repository: harbor.orcamento.local/orcamento/orcamento-backend
  pullPolicy: IfNotPresent
  tag: "hml-latest"

service:
  type: ClusterIP
  port: 8045

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

env:
  - name: SPRING_PROFILES_ACTIVE
    value: hml

app:
  database:
    host: mysql-external.orcamento.svc.cluster.local
    port: 3306
    name: orcamento-hml
    username: root
    password: ""
    existingSecret: orcamento-backend-hml-secrets
    existingSecretKey: SPRING_DATASOURCE_PASSWORD

  cors:
    allowedOrigins: "http://hml.orcamento.local,http://api.hml.orcamento.local,http://localhost:8080,*"

  jwt:
    expirationMs: 1800000
    existingSecret: orcamento-backend-hml-secrets
    existingSecretKey: JWT_SECRET

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplay.meuorcamento@gmail.com
    password: ""
    from: noreplay.meuorcamento@gmail.com
    existingSecret: orcamento-backend-hml-secrets
    existingSecretKey: SPRING_MAIL_PASSWORD

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 45
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

configMap:
  create: true
  applicationYaml: ""
