replicaCount: 1

image:
  repository: harbor.orcamento.local/orcamento/orcamento-frontend
  pullPolicy: IfNotPresent
  tag: "1.1.11"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "orcamento-frontend"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: orcamento.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - orcamento.local
  rules: []

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

configMap:
  enabled: true
  data:
    VUE_APP_API_URL: "http://api.orcamento.local/api/v1"
    VUE_APP_ENV: "PROD"

env: []
