CREATE TABLE conciliacao_ofx_processamento (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    conta_corrente_id BIGINT NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NULL,
    tamanho_arquivo BIGINT NOT NULL,
    hash_arquivo VARCHAR(64) NULL,
    banco_id_ofx VARCHAR(255) NULL,
    conta_id_ofx VARCHAR(255) NULL,
    periodo_inicio DATE NULL,
    periodo_fim DATE NULL,
    tolerancia_dias INT NOT NULL,
    tolerancia_valor DECIMAL(19,2) NOT NULL,
    tolerancia_valor_minimo DECIMAL(19,2) NOT NULL,
    conciliados_quantidade INT NOT NULL,
    banco_sem_pagamento_quantidade INT NOT NULL,
    pagamento_sem_banco_quantidade INT NOT NULL,
    ambiguos_quantidade INT NOT NULL,
    receitas_conciliadas_quantidade INT NOT NULL,
    transferencias_conciliadas_quantidade INT NOT NULL,
    creditos_origem_cartao_quantidade INT NOT NULL,
    banco_sem_receita_quantidade INT NOT NULL,
    receita_sem_banco_quantidade INT NOT NULL,
    receitas_ambiguas_quantidade INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    mensagem_erro VARCHAR(1000) NULL,
    processado_em DATETIME(6) NOT NULL,
    PRIMARY KEY (id)
);
